"""The NIL edge: the six endpoints, generic across any backend. GENERATED by nilscript scaffold.

Enforces the contract — envelope + bearer auth, no side effects on PROPOSE, idempotent COMMIT, a
real write surfaced as an HMAC-signed EVENT, bare {data} for QUERY. It calls the translation core
(translate.py) and the system client (system.py); it contains no backend specifics. Do not edit —
regenerate with `nilscript scaffold-shim`.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import uuid4

from fastapi import Body, FastAPI, Header, HTTPException, Response

from odoo_nil_adapter import governance
from odoo_nil_adapter.compensation import COMPENSATIONS, compensate
from odoo_nil_adapter.manifest import apply_transport_quirks, overlay_requirements
from odoo_nil_adapter.state import ShimState
from odoo_nil_adapter.system import SystemClient, SystemError
from odoo_nil_adapter.tenant_routing import bind_tenant
from odoo_nil_adapter.translate import (
    QUERY_VERBS,
    RESOURCE_VERBS,
    RESOURCES,
    WRITE_VERBS,
    entity_ref,
)

NIL = "0.1"
SYSTEM = "odoo_crm"


def _now() -> str:
    return datetime.now(UTC).isoformat()


def _resource_phrase(op: str, target: str, args: dict[str, Any]) -> tuple[str, str]:
    """Bilingual preview for a generic resource.* op (no per-verb authoring)."""
    rid = args.get("id", "")
    data = args.get("data") or {}
    if op == "create":
        return f"Create {target} record {data}", f"إنشاء سجل في {target}"
    if op == "update":
        return f"Update {target}/{rid} → {data}", f"تحديث {target}/{rid}"
    return f"Delete {target}/{rid}", f"حذف {target}/{rid}"


# An agent may name an entity in generic terms (client, customer, vendor) rather than the exact Odoo
# model. We resolve it to whatever THIS adapter actually DECLARES (its writable model set) — never a
# hardcoded per-backend table. A noun maps to a concept; a concept matches any declared model whose
# name carries one of the concept's words. So `customer` → `res.partner` (carries "partner"), while an
# exact model like `res.partner` passes straight through. Identical logic ships in every adapter; here
# it feeds ONLY the generic resource.* spine (nil.* reads already resolve `about` via the IntentResolver).
_NOUN_CONCEPT = {
    "client": "client", "customer": "client", "contact": "client", "partner": "client",
    "res.partner": "client", "company": "client", "account": "client", "party": "client",
    "invoice": "invoice", "bill": "invoice", "account.move": "invoice",
    "product": "product", "item": "product", "product.product": "product",
    "supplier": "supplier", "vendor": "supplier",
    "payment": "payment", "purchase": "purchase", "purchase_invoice": "purchase",
}
_CONCEPT_WORDS = {
    "client": ("client", "customer", "partner", "contact", "party"),
    "invoice": ("invoice", "bill", "move"),
    "product": ("product", "item"),
    "supplier": ("supplier", "vendor"),
    "payment": ("payment",),
    "purchase": ("purchase",),
}


def _resolve_target(name: Any) -> Any:
    """Normalize an entity noun to a DECLARED Odoo model — generic, driven by this adapter's own
    writable targets: exact (case-insensitive), singular↔plural, concept synonym, then substring. An
    unrecognized value is returned unchanged (governance still refuses it downstream)."""
    if not isinstance(name, str) or not name:
        return name
    declared = sorted(governance.writable_targets())
    if name in declared:
        return name
    low = name.strip().lower()
    for d in declared:  # case-insensitive exact, then singular↔plural
        dl = d.lower()
        if dl == low or dl == low + "s" or low == dl + "s":
            return d
    concept = _NOUN_CONCEPT.get(low)  # concept synonym → a declared model that carries the concept
    if concept:
        for d in declared:
            if any(w in d.lower() for w in _CONCEPT_WORDS.get(concept, ())):
                return d
    for d in declared:  # last resort: substring either way
        if low in d.lower() or d.lower() in low:
            return d
    return name


_ID_FIELDS = ("code", "name", "slug", "title", "sku", "email")


def _resolve_id(client: SystemClient, target: str, value: str) -> str | None:
    """Accept a real record id OR a human identifier (code/name/…) → real id, or None if ambiguous."""
    if not value:
        return None
    if client.get(target, value) is not None:
        return value
    for field in _ID_FIELDS:
        try:
            rows = client.list(target, {field: value})
        except SystemError:
            continue
        hits = [r for r in rows if str(r.get(field, "")) == str(value)]
        if len(hits) == 1:
            return str(hits[0].get("id") or hits[0].get("name"))
    return None


_HTML_TAG = re.compile(r"<[^>]+>")


def _field_landed(actual: Any, intended: Any) -> bool:
    """Did the SSOT actually take the intended value? Tolerates backend normalization (html wrapping,
    formatting) but treats empty/false-where-a-value-was-intended as a hard miss — the exact signature
    of a silently dropped write (e.g. country_id:false). Equality first, then a tag-stripped contains."""
    if actual == intended:
        return True
    intended_s = str(intended).strip() if intended is not None else ""
    if not intended_s:  # nothing meaningful was asked for
        return True
    actual_s = _HTML_TAG.sub("", str(actual if actual not in (None, False) else "")).strip()
    return intended_s == actual_s or intended_s in actual_s


def _verify_and_diff(
    client: SystemClient, doctype: str, record_id: str,
    before: dict[str, Any], native: dict[str, Any],
) -> tuple[list[str], list[dict[str, Any]]]:
    """One SSOT read-back → (unverified_fields, per-field before→after diff). The diff carries, for
    every written field, what it WAS, what was ASKED, and what actually LANDED — so the control plane
    can show a silent drop (country_id: السعودية → false) field-by-field, not just name it in a list.
    `unverified` (a field that did not land) still drives the verified/partial verdict, unchanged."""
    after = client.get(doctype, record_id) or {}
    meta_by_field = {f.get("name"): f for f in (client.schema(doctype) or [])}
    unverified: list[str] = []
    diff: list[dict[str, Any]] = []
    for field, intended in native.items():
        landed = _field_landed(after.get(field), intended)
        if not landed:
            unverified.append(field)
        row: dict[str, Any] = {"field": field, "before": before.get(field), "requested": intended,
                               "after": after.get(field), "verified": landed}
        # Fault B (reference legibility): re-resolve the value that actually LANDED to its human
        # label, so the Observation reads "country_id → Türkiye (224)" — grounded in the SSOT, with
        # nothing left for the agent to fabricate. before_label gives the reversible prior meaning.
        meta = meta_by_field.get(field) or {}
        if meta.get("relation") or meta.get("options"):
            relation = meta.get("relation")
            for col in ("before", "after"):
                raw = (before if col == "before" else after).get(field)
                label = (_label_for(client, relation, raw) if relation
                         else _option_label(meta["options"], raw)) if raw not in (None, "", False) else None
                if label is not None:
                    row[f"{col}_label"] = label
        diff.append(row)
    return unverified, diff


def _hash_snap(snapshot: dict[str, Any]) -> str:
    """Canonical hash of an SSOT field snapshot — the state-witness bound at PROPOSE and rechecked at
    COMMIT. Empty snapshot → '' (no precondition, e.g. a create). Sibling of reference-legibility: the
    kernel refuses to commit against a world that drifted since the human approved the preview (TOCTOU)."""
    if not snapshot:
        return ""
    blob = json.dumps(snapshot, sort_keys=True, ensure_ascii=False, default=str, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def _before_image_reversal(
    client: SystemClient, doctype: str, record_id: str, native: dict[str, Any]
) -> tuple[dict[str, Any], dict[str, Any]]:
    """A COMPENSABLE reversal that restores ONLY the fields a write is about to patch — so ROLLBACK
    never clobbers an unrelated concurrent edit. Returns (reversal, before_image): the before-image
    is reused as the diff's 'before' column, so the patch is read from the SSOT exactly once."""
    before = client.get(doctype, record_id) or {}
    before_changed = {field: before.get(field) for field in native}
    reversal = {"resource": True, "rev_verb": "resource.update",
                "rev_args": {"target": doctype, "id": record_id, "data": before_changed}}
    return reversal, before


def _resolve_reference(client: SystemClient, model: str, value: Any) -> int:
    """Resolve a human dropdown value (a many2one: country/state/…) to the backend record id the
    field actually accepts — never write the raw string into a relational field. Strategy: a bare
    numeric id passes straight through (already resolved); a short alpha token is tried as an ISO code;
    otherwise a name match, preferring an exact (case-insensitive) hit. Zero matches => UNRESOLVED,
    many => AMBIGUOUS — both raise (the edge turns them into an honest terminal failure, no write)."""
    v = str(value).strip()
    if not v:
        raise SystemError(f"empty reference for {model}")
    if v.isdigit():
        return int(v)
    candidates: list[dict[str, Any]] = []
    if 2 <= len(v) <= 3 and v.isalpha():
        candidates = client.search(model, [["code", "=", v.upper()]], fields=("id", "name", "code"), limit=2)
    if not candidates:
        candidates = client.search(model, [["name", "ilike", v]], fields=("id", "name", "code"), limit=8)
    exact = [c for c in candidates if str(c.get("name", "")).strip().lower() == v.lower()]
    pool = exact or candidates
    if not pool:
        raise SystemError(f"UNRESOLVED_REFERENCE: no {model} matches {value!r}")
    if len(pool) > 1:
        raise SystemError(f"AMBIGUOUS_REFERENCE: {len(pool)} {model} records match {value!r}")
    rid = pool[0].get("id")
    if rid is None:
        raise SystemError(f"UNRESOLVED_REFERENCE: {model} match for {value!r} has no id")
    return int(rid)


def _resolve_option(options: list[dict[str, Any]], value: Any) -> Any:
    """Resolve a human term to a selection field's stored key (bucket B): "متاح"/"Available" →
    "available". Matches the stored key directly, else the label (case-insensitive) or the key text.
    Zero matches => UNRESOLVED, many => AMBIGUOUS — never write a value outside the allowed set."""
    v = str(value).strip()
    if not v:
        raise SystemError("empty selection value")
    keys = [o.get("value") for o in options]
    if value in keys or v in [str(k) for k in keys]:  # already the stored key
        return value
    hits = [
        o.get("value") for o in options
        if str(o.get("label", "")).strip().lower() == v.lower()
        or str(o.get("value", "")).strip().lower() == v.lower()
    ]
    if not hits:
        raise SystemError(f"UNRESOLVED_OPTION: {value!r} not in allowed values {[str(k) for k in keys]}")
    if len({str(h) for h in hits}) > 1:
        raise SystemError(f"AMBIGUOUS_OPTION: {value!r} matches multiple options")
    return hits[0]


def _is_x2many_commands(value: Any) -> bool:
    """True for an Odoo x2many write payload — a list of command tuples like [(0, 0, {...})] / (6, 0,
    [ids]). These are NOT scalar references and must NOT be run through reference/option resolution
    (doing so treats '(0, 0, {...})' as a name to look up → spurious refusal / 500). Lines are passed
    through to the backend verbatim."""
    return isinstance(value, (list, tuple)) and any(isinstance(el, (list, tuple)) for el in value)


def _resolve_writes(client: SystemClient, doctype: str, native: dict[str, Any]) -> dict[str, Any]:
    """Schema-driven resolution of every written field to the value the backend actually accepts —
    a selection value → its stored key (B), a many2one value → the referenced record id (C). Driven
    by field_meta from schema(); a plain scalar with no constraint passes through, and an
    already-resolved id/key resolves to itself (idempotent). A backend that exposes no schema simply
    leaves values untouched (declared `references` still cover the critical ones). Raises on an
    unresolvable/ambiguous value → honest terminal failure, never a silently wrong write."""
    meta_by_field = {f.get("name"): f for f in (client.schema(doctype) or [])}
    resolved = dict(native)
    for field, value in native.items():
        if value in (None, "") or _is_x2many_commands(value):  # lines pass through verbatim
            continue
        meta = meta_by_field.get(field) or {}
        # D (multi-value): a list/tuple value resolves element-by-element — many2many/tag fields
        # become a list of referenced ids, multi-selects a list of keys. Cardinality is preserved.
        if meta.get("relation"):
            resolved[field] = ([_resolve_reference(client, meta["relation"], v) for v in value]
                               if isinstance(value, (list, tuple))
                               else _resolve_reference(client, meta["relation"], value))
        elif meta.get("options"):
            resolved[field] = ([_resolve_option(meta["options"], v) for v in value]
                               if isinstance(value, (list, tuple))
                               else _resolve_option(meta["options"], value))
    return resolved


def _option_label(options: list[dict[str, Any]], value: Any) -> str | None:
    """Best-effort label for a selection value (its stored key OR its label) — None if not an option."""
    v = str(value).strip().lower()
    for opt in options:
        if str(opt.get("value")).lower() == v or str(opt.get("label", "")).strip().lower() == v:
            return opt.get("label")
    return None


def _label_for(client: SystemClient, model: str, value: Any) -> str | None:
    """Best-effort human label for a stored relational value (an id OR a name) — the inverse of
    _resolve_reference, for the legible echo (docs/reference-legibility.md). Never raises and never
    guesses: returns None unless the value labels to exactly one record. The Choice Gate, not this,
    owns ambiguity refusal — legibility only makes an already-decided value readable."""
    v = str(value).strip()
    if not v:
        return None
    try:
        if v.isdigit():
            rows = client.search(model, [["id", "=", int(v)]], fields=("id", "name", "code"), limit=1)
        else:
            rows = client.search(model, [["name", "ilike", v]], fields=("id", "name", "code"), limit=8)
            rows = [r for r in rows if str(r.get("name", "")).strip().lower() == v.lower()] or rows
    except SystemError:
        return None
    return _label(rows[0]) if len(rows) == 1 else None


def _legible(client: SystemClient, doctype: str, fields: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """{field: {value, label}} for every constrained (relation/selection) field written in `fields` —
    the symmetric reference-legibility echo (docs/reference-legibility.md). Used on PROPOSE (Fault A:
    an opaque foreign key never crosses approval illegibly) and on read-back (Fault B: the receipt is
    built from a live re-resolution of the landed value, not from agent narration). Schema-driven;
    plain scalars, multi-values, and unlabelable values are omitted."""
    meta_by_field = {f.get("name"): f for f in (client.schema(doctype) or [])}
    echo: dict[str, dict[str, Any]] = {}
    for field, value in fields.items():
        if value in (None, "") or isinstance(value, (list, tuple)):
            continue
        meta = meta_by_field.get(field) or {}
        label = (_label_for(client, meta["relation"], value) if meta.get("relation")
                 else _option_label(meta["options"], value) if meta.get("options") else None)
        if label is not None:
            echo[field] = {"value": value, "label": label}
    return echo


class EventEmitter(Protocol):
    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None: ...


class CapturingEmitter:
    """Test/proof emitter: records pushed events instead of sending them."""

    def __init__(self) -> None:
        self.events: list[tuple[int, dict[str, Any]]] = []

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        self.events.append((sequence, event_envelope))


class HttpEventEmitter:
    """Real emitter: HMAC-SHA256 over the raw body + a monotonic per-workspace sequence header."""

    def __init__(self, webhook_url: str, secret: str, *, source: str = "") -> None:
        self._url = webhook_url
        self._secret = secret.encode("utf-8")
        self._source = source  # tags events in the control plane (e.g. "playground" vs "mcp")

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        import httpx

        raw = json.dumps(event_envelope, separators=(",", ":")).encode("utf-8")
        signature = hmac.new(self._secret, raw, hashlib.sha256).hexdigest()
        headers = {
            "Content-Type": "application/json",
            "X-NIL-Signature": signature,
            "X-NIL-Sequence": str(sequence),
        }
        if self._source:
            headers["X-NIL-Source"] = self._source
        httpx.post(self._url, content=raw, headers=headers, timeout=10.0)


def _envelope(performative: str, env: dict[str, Any], body: dict[str, Any]) -> dict[str, Any]:
    return {
        "nil": NIL,
        "id": uuid4().hex,
        "performative": performative,
        "grant": env.get("grant", ""),
        "workspace": env.get("workspace", ""),
        "ts": _now(),
        "body": body,
    }


def _refusal(env: dict[str, Any], code: str, message: str, field: str | None = None,
             candidates: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    body: dict[str, Any] = {"outcome": "refusal", "code": code, "message": message}
    if field is not None:
        body["field"] = field
    if candidates:  # Choice Gate: the live option set the agent must pick from
        body["candidates"] = candidates
    return _envelope("PROPOSAL", env, body)


def _choice_gate(client: SystemClient, doctype: str, native: dict[str, Any],
                 env: dict[str, Any]) -> dict[str, Any] | None:
    """Choice Gate (PROPOSE-time). Every constrained field's value must resolve to a real member of
    its live set. If one can't, return a refusal carrying the candidate options — so the intelligent
    agent picks the right member in ANY language/phrasing and re-proposes, never a hallucinated or
    silently-wrong value. None = every value is a valid choice. Resolution intelligence lives in the
    agent; the kernel/adapter only guarantees the chosen value is real. Mirrors _resolve_writes."""
    meta_by_field = {f.get("name"): f for f in (client.schema(doctype) or [])}
    for field, value in native.items():
        if value in (None, "") or _is_x2many_commands(value):  # x2many lines aren't scalar references
            continue
        meta = meta_by_field.get(field) or {}
        for v in (value if isinstance(value, (list, tuple)) else [value]):
            if meta.get("relation"):
                gate = _gate_relation(client, env, field, meta["relation"], v)
                if gate is not None:
                    return gate
            elif meta.get("options"):
                gate = _gate_option(env, field, meta["options"], v)
                if gate is not None:
                    return gate
    return None


def _gate_relation(client: SystemClient, env: dict[str, Any], field: str, model: str,
                   value: Any) -> dict[str, Any] | None:
    """Validate a relational value; on failure refuse with up to 8 close matches (AMBIGUOUS), or — if
    nothing matches (e.g. an Arabic name vs an English res.country) — point the agent at the full list
    to query and choose from (INVALID_ARGS). Candidates obey the kernel's Candidate schema: {id, name}."""
    try:
        _resolve_reference(client, model, value)
        return None
    except SystemError:
        rows = client.search(model, [["name", "ilike", str(value)]], fields=("id", "name", "code"), limit=8)
        cands = [{"id": str(r.get("id")), "name": _label(r)} for r in rows if r.get("id") is not None]
        if cands:
            return _refusal(env, "AMBIGUOUS", f"{field}: '{value}' matched several {model} — pick one of the "
                            "candidates and re-propose.", field=field, candidates=cands)
        return _refusal(env, "INVALID_ARGS", f"{field}: '{value}' did not match any {model}. Query "
                        f"resource.read target={model} for the full list, choose the id, and re-propose.",
                        field=field)


def _gate_option(env: dict[str, Any], field: str, options: list[dict[str, Any]], value: Any) -> dict[str, Any] | None:
    """Validate a selection value; on failure refuse with the allowed values as candidates (≤8)."""
    try:
        _resolve_option(options, value)
        return None
    except SystemError:
        cands = [{"id": str(o.get("value")), "name": str(o.get("label") or o.get("value"))}
                 for o in options[:8]]
        return _refusal(env, "INVALID_ARGS", f"{field}: '{value}' is not an allowed value — choose one of "
                        "the candidates and re-propose.", field=field, candidates=cands)


def _label(row: dict[str, Any]) -> str:
    name = str(row.get("name") or row.get("id") or "")
    code = row.get("code")
    return f"{name} ({code})" if code else name


def create_app(client: SystemClient, emitter: EventEmitter, *, bearer: str | None) -> FastAPI:
    app = FastAPI(title="odoo-nil-adapter shim", version="0.1.0")
    state = ShimState()
    apply_transport_quirks(client)  # manifest-driven: e.g. drop Expect: 100-continue (plan §4.4)
    governance.load_grants_from_env()  # persist per-tenant grants from config (onboarding), not runtime

    def _auth(authorization: str | None) -> None:
        if bearer is None:  # permissive dev wiring behind a trusted gateway
            return
        # constant-time compare — a `!=` would leak the token via timing.
        if not hmac.compare_digest(authorization or "", f"Bearer {bearer}"):
            raise HTTPException(status_code=401, detail="unauthorized")

    @app.post("/nil/v0.1/propose")
    def propose(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {})
        verb_name = body.get("verb")
        args = body.get("args", {}) or {}
        tenant = env.get("workspace") or None  # the per-tenant grant scope (SaaS); None = shipped skeleton
        bind_tenant(tenant)  # route this request's backend calls to THIS workspace's vault creds
        # Generic op=method (universal workflow actions): call a governed model method on a record —
        # action_post, button_validate, action_confirm, … — with NO per-action verb. Gated by the
        # method allow-list (default-deny), so an unlisted/financial method is unexpressible.
        if verb_name == "resource.method":
            target, method, rid = _resolve_target(args.get("target")), args.get("method"), args.get("id")
            if not target:
                return _refusal(env, "INVALID_ARGS", "missing required arg: target", field="target")
            if not method:
                return _refusal(env, "INVALID_ARGS", "missing required arg: method", field="method")
            if not rid:
                return _refusal(env, "INVALID_ARGS", "missing required arg: id", field="id")
            tier = governance.method_tier(target, method, tenant=tenant)
            if tier is None:
                return _refusal(env, "UNKNOWN_VERB",
                                f"method '{method}' on '{target}' is not granted by this adapter's governance policy")
            if not client.exists(target):
                return _refusal(env, "UPSTREAM_UNAVAILABLE",
                                f"backend target '{target}' is not provisioned on this system")
            pid = uuid4().hex[:16]
            # Persist the RESOLVED target so COMMIT — which reads stored args.target to call the
            # governed method — hits the real model, not the raw noun the agent used.
            state.proposals[pid] = {"verb": verb_name, "args": {**args, "target": target}, "resource_method": True, "tier": tier}
            return _envelope("PROPOSAL", env, {
                "outcome": "proposal", "id": pid, "verb": verb_name, "tier": tier,
                "preview": {"en": f"Call {method} on {target}/{rid}",
                            "ar": f"استدعاء {method} على {target}/{rid}"},
                "resolved": args, "modifiable": [], "expires_at": _now()})
        # Generic resource.* CRUD (universal): target/id/data from args, no per-verb doctype.
        if isinstance(verb_name, str) and verb_name.startswith("resource."):
            op = verb_name.split(".", 1)[1]
            if op not in ("create", "update", "delete"):
                return _refusal(env, "UNKNOWN_VERB", f"unknown resource op: {op}")
            target = _resolve_target(args.get("target"))
            if not target:
                return _refusal(env, "INVALID_ARGS", "missing required arg: target", field="target")
            # Skeleton bound (advertised ≡ committable): the WRITE ceiling is governance policy, not the
            # read surface. A provisioned-but-ungranted model (account.payment, hr.employee, …) reads
            # via nil.* but is unexpressible for writes — refused here, never committed. Lifting the
            # read ceiling (dynamic discovery) does NOT lift the write ceiling. Guarantee 2 holds.
            tier = governance.write_tier(target, op, tenant=tenant)
            if tier is None:
                return _refusal(env, "UNKNOWN_VERB",
                                f"target '{target}' is not writable under this adapter's governance policy")
            if op in ("update", "delete") and not args.get("id"):
                return _refusal(env, "INVALID_ARGS", "missing required arg: id", field="id")
            if op in ("create", "update") and not isinstance(args.get("data"), dict):
                return _refusal(env, "INVALID_ARGS", "missing required arg: data", field="data")
            if not client.exists(target):
                return _refusal(env, "UPSTREAM_UNAVAILABLE",
                                f"backend target '{target}' is not provisioned on this system")
            if op in ("create", "update"):  # Choice Gate: constrained values must be real members
                gate = _choice_gate(client, target, args.get("data") or {}, env)
                if gate is not None:
                    return gate
            pid = uuid4().hex[:16]
            # Persist the RESOLVED target so COMMIT — which reads stored args.target for the CRUD
            # write — hits the real model, not the raw noun the agent used.
            state.proposals[pid] = {"verb": verb_name, "args": {**args, "target": target}, "resource": True}
            # State-witness (TOCTOU): bind the proposal to the SSOT values it previewed, so a COMMIT
            # after a delayed approval against a changed world fails closed instead of writing stale.
            if op == "update":
                rid0 = _resolve_id(client, target, str(args.get("id", "")))
                if rid0 is not None:
                    rec0 = client.get(target, rid0) or {}
                    state.proposals[pid]["witness"] = _hash_snap({f: rec0.get(f) for f in (args.get("data") or {})})
            en, ar = _resource_phrase(op, target, args)
            # Fault A (reference legibility): echo each relational/selection field by resolved name,
            # so a bare foreign key (e.g. country_id: 224) is approved as "country_id → Türkiye",
            # never as a magic number the agent can mislabel.
            refs = _legible(client, target, args.get("data") or {})
            if refs:
                tail = " · ".join(f"{f} → {x['label']}" for f, x in refs.items())
                en, ar = f"{en} · {tail}", f"{ar} · {tail}"
            return _envelope("PROPOSAL", env, {
                "outcome": "proposal", "id": pid, "verb": verb_name,
                "tier": tier,
                "preview": {"en": en, "ar": ar},
                "resolved": {**args, "references": refs} if refs else args,
                "modifiable": [], "expires_at": _now()})

        verb = WRITE_VERBS.get(verb_name)
        if verb is None:
            return _refusal(env, "UNKNOWN_VERB", f"verb not supported by this backend: {verb_name}")
        # A curated (semantic) verb is a deliberate grant — but it still obeys the operator's module
        # scope: a verb on an out-of-scope module is unexpressible, same as the generic path.
        if not governance.module_enabled(verb.doctype):
            return _refusal(env, "UNKNOWN_VERB",
                            f"verb '{verb_name}' targets module-scoped-out model '{verb.doctype}'")
        missing = verb.missing(args)
        if missing:
            return _refusal(env, "INVALID_ARGS", f"missing required arg: {missing[0]}", field=missing[0])
        # An effect whose arithmetic is undefined is not a small effect — it is NO effect. A verb that
        # cannot compute its own payload (a landed cost over a received quantity of zero) must say so
        # HERE, before a human approves it, instead of writing an empty doc and reporting success.
        nonpositive = verb.nonpositive(args)
        if nonpositive:
            return _refusal(
                env, "INVALID_ARGS",
                f"'{nonpositive[0]}' must be a number greater than zero — the effect cannot be "
                f"computed otherwise", field=nonpositive[0])
        # Preflight (universal): refuse at PROPOSE if the native target isn't provisioned.
        if not client.exists(verb.doctype):
            return _refusal(env, "UPSTREAM_UNAVAILABLE",
                            f"backend target '{verb.doctype}' is not provisioned on this system")
        # Choice Gate: every constrained field's value must resolve to a real member of its live set.
        # Build the native view the write will produce (incl. declared references) and validate it;
        # an unresolvable/ambiguous value refuses WITH the candidate options so the agent re-picks.
        gate_native = dict(verb.to_native(args))
        for nil_arg, native_field, model in verb.references:
            if args.get(nil_arg) not in (None, ""):
                gate_native[native_field] = args[nil_arg]
        gate = _choice_gate(client, verb.doctype, gate_native, env)
        if gate is not None:
            return gate
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {"verb": verb_name, "args": args}  # NO write — dry-run only
        # Honesty at PROPOSE: if the verb declares the args it can write, surface anything outside
        # that set as `ignored` — an unwritable field (e.g. country) is flagged, never silently kept.
        ignored = [k for k in args if k not in verb.supported_args] if verb.supported_args else []
        # Fault A (reference legibility): echo the constrained native fields by resolved name, so the
        # preview reads "… · country_id → Qatar (QA)" and `resolved.references` carries the meaning.
        refs = _legible(client, verb.doctype, gate_native)
        preview = verb.preview(args)
        if refs:
            tail = " · ".join(f"{f} → {x['label']}" for f, x in refs.items())
            preview = {loc: f"{txt} · {tail}" for loc, txt in preview.items()}
        body: dict[str, Any] = {
            "outcome": "proposal",
            "id": proposal_id,
            "verb": verb_name,
            "tier": verb.tier,
            "preview": preview,
            "resolved": {**args, "references": refs} if refs else args,
            "modifiable": [],
            "expires_at": _now(),
        }
        if ignored:
            body["ignored"] = ignored
        return _envelope("PROPOSAL", env, body)

    @app.post("/nil/v0.1/commit")
    def commit(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        # Bind the tenant at the TOP of the handler: each request runs in a fresh ContextVar
        # context, so the bind done at PROPOSE does not carry over — without this, the generic
        # create/update/delete commit path hit the vault resolver tenant-less and every write
        # failed "no workspace in the request" (while the run still reported completed).
        bind_tenant(env.get("workspace") or None)
        body = env.get("body", {})
        key = body.get("idempotency_key", "")
        if key in state.ledger:  # retried COMMIT — replay, no second write
            return _envelope("STATUS", env, {**state.ledger[key], "replayed": True})
        proposal_id = body.get("proposal", "")
        stored = state.proposals.get(proposal_id)
        if stored is None:
            return _refusal(env, "EXPIRED", f"unknown or expired proposal: {proposal_id}")
        if stored.get("resource_method"):  # generic workflow-method path — invoke, no synthesized reversal
            target = stored["args"]["target"]
            method = stored["args"]["method"]
            params = stored["args"].get("params") or {}
            rid = str(stored["args"].get("id", ""))
            try:
                rid = _resolve_id(client, target, rid) or rid
                client.call_method(target, rid, method, params)
            except (SystemError, NotImplementedError) as exc:
                print(f"[shim] METHOD FAILED {target}.{method} -> {exc}", flush=True)
                return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
            # Reversibility is declared per (model, method) in governance: a method with a registered
            # inverse (action_post→button_draft, action_confirm→action_cancel) is COMPENSABLE — we mint a
            # token that calls the inverse on ROLLBACK; one with no inverse stays honestly IRREVERSIBLE.
            tenant = env.get("workspace") or None
            bind_tenant(tenant)  # route this request's backend calls to THIS workspace's vault creds
            reverse = governance.method_reverse(target, method, tenant=tenant)
            if reverse:
                tok = uuid4().hex[:16]
                state.compensations[tok] = {"resource_method": True, "target": target, "id": rid,
                                            "method": reverse, "tier": stored.get("tier", "HIGH")}
                comp_block = {"reversibility": "COMPENSABLE", "token": tok}
            else:
                comp_block = {"reversibility": "IRREVERSIBLE"}
            result = {"claim": "success", "changed": True, "verified": False,
                      "entity": {"type": stored["verb"], "id": rid, "url": f"/{target}/{rid}"},
                      "ssot": {"system": SYSTEM, "read_after_write": False, "method": method},
                      "compensation": comp_block}
            status_body = {"proposal": proposal_id, "state": "executed", "replayed": False,
                           "compensation": comp_block, "result": result}
            state.ledger[key] = status_body
            state.executed.add(proposal_id)
            emitter.emit(_envelope("EVENT", env, {"event": "executed", "severity": "info",
                         "proposal": proposal_id, "result": result}), state.next_sequence(env.get("workspace", "")))
            return _envelope("STATUS", env, status_body)
        if stored.get("resource"):  # generic CRUD path — dispatch by args.target, synthesize result + reversal
            op = stored["verb"].split(".", 1)[1]
            target = stored["args"]["target"]
            rid = str(stored["args"].get("id", ""))
            data = stored["args"].get("data") or {}
            before: dict[str, Any] = {}
            try:
                data = _resolve_writes(client, target, data)  # B/C resolution before any write
                if op == "create":
                    created = client.create(target, data)
                    rid = str(created.get("id") or created.get("name") or "")
                    rev_verb, rev_args, rev = "resource.delete", {"target": target, "id": rid}, "REVERSIBLE"
                else:
                    resolved = _resolve_id(client, target, rid)
                    if resolved is None:
                        return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
                    rid = resolved
                    before = client.get(target, rid) or {}
                    # State-witness recheck: if the SSOT drifted since PROPOSE, fail closed (no write).
                    if op == "update" and stored.get("witness"):
                        if stored["witness"] != _hash_snap({f: before.get(f) for f in data}):
                            return _refusal(env, "PRECONDITION_FAILED",
                                            "state changed since this proposal was previewed; "
                                            "re-propose to get a fresh preview and re-approve")
                    if op == "update":
                        client.update(target, rid, data)
                        rev_verb, rev_args, rev = "resource.update", {"target": target, "id": rid, "data": before}, "COMPENSABLE"
                    else:
                        client.delete(target, rid)
                        rev_verb, rev_args, rev = "resource.create", {"target": target, "data": before}, "COMPENSABLE"
            except (SystemError, NotImplementedError) as exc:
                print(f"[shim] RESOURCE WRITE FAILED {stored['verb']} -> {exc}", flush=True)
                return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
            comp_block = {"reversibility": rev}
            tok = uuid4().hex[:16]
            state.compensations[tok] = {"resource": True, "rev_verb": rev_verb, "rev_args": rev_args}
            comp_block["token"] = tok
            # EARN verified here too: create/update re-read and compare `data`; delete confirms absence.
            field_diff: list[dict[str, Any]] = []
            if op == "delete":
                unverified, verified = [], client.get(target, rid) is None
            else:
                unverified, field_diff = _verify_and_diff(client, target, rid, before, data)
                verified = not unverified
            ssot = {"system": SYSTEM, "read_after_write": True}
            if unverified:
                ssot["unverified_fields"] = unverified
            if field_diff:
                ssot["fields"] = field_diff
            result = {"claim": "success" if verified else "partial", "changed": True, "verified": verified,
                      "entity": {"type": stored["verb"], "id": rid, "url": f"/{target}/{rid}"},
                      "ssot": ssot, "compensation": comp_block}
            if unverified:
                result["unverified_fields"] = unverified
            status_body = {"proposal": proposal_id, "state": "executed", "replayed": False,
                           "compensation": comp_block, "result": result}
            state.ledger[key] = status_body
            state.executed.add(proposal_id)
            emitter.emit(_envelope("EVENT", env, {"event": "executed", "severity": "info",
                         "proposal": proposal_id, "result": result}), state.next_sequence(env.get("workspace", "")))
            return _envelope("STATUS", env, status_body)
        verb = WRITE_VERBS[stored["verb"]]
        comp_spec = COMPENSATIONS.get(stored["verb"], {})
        comp_override: dict[str, Any] | None = None  # a before-image reversal the op handler synthesizes
        before_image: dict[str, Any] = {}  # pre-write SSOT snapshot → the diff's 'before' column
        try:
            # to_native is inside the try so an UNFILLED stub (NotImplementedError) is a clean
            # terminal failure, not a 500 — the conformance proof reads it as non-conformance.
            native = overlay_requirements(stored["verb"], verb.to_native(stored["args"]))  # manifest pre-fill
            # Resolve declared many2one args (e.g. country → country_id) to backend reference ids
            # BEFORE the write — a relational field rejects raw text. An unresolvable/ambiguous value
            # raises SystemError here, becoming an honest terminal failure (no silent write).
            for nil_arg, native_field, model in verb.references:
                if stored["args"].get(nil_arg) not in (None, ""):
                    native[native_field] = _resolve_reference(client, model, stored["args"][nil_arg])
            # Then resolve EVERY written field against the live schema — selection → key (B),
            # any undeclared many2one → referenced id (C). Declared references above are idempotent here.
            native = _resolve_writes(client, verb.doctype, native)
            # Write-path dispatch by the verb's DECLARED execution strategy (translate.py), not by
            # guessing from the name prefix — name inference only ever modelled CRUD. The record id
            # for update/delete is the verb's first required arg (e.g. lead_id, contact_id).
            if verb.op == "delete":
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw  # accept id or human identifier
                client.delete(verb.doctype, record_id)
                created = {"name": record_id}
            elif verb.op == "update":
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw
                if comp_spec.get("strategy") == "before_image":
                    comp_override, before_image = _before_image_reversal(client, verb.doctype, record_id, native)
                created = client.update(verb.doctype, record_id, native)
            elif verb.op == "upsert":
                # Probe the dedup keys (in order) for an existing record. A single hit ⇒ update it in
                # place (COMPENSABLE before-image); no hit ⇒ create (REVERSIBLE by the verb's delete).
                match_id: str | None = None
                for field in verb.dedup_keys:
                    value = native.get(field)
                    if not value:
                        continue
                    hits = client.search(verb.doctype, [[field, "=", value]], limit=2)
                    if len(hits) > 1:
                        # Ambiguous: >1 record matches this key. Guessing one (or creating a third)
                        # corrupts the identity graph — refuse instead. Terminal, no write performed.
                        raise SystemError(f"upsert ambiguous: {len(hits)}+ records match {field}={value!r}")
                    if len(hits) == 1:
                        match_id = str(hits[0].get("id") or hits[0].get("name") or "")
                        break
                if match_id is None:
                    created = client.create(verb.doctype, native)  # leaves comp_override None → verb-mapped delete
                else:
                    comp_override, before_image = _before_image_reversal(client, verb.doctype, match_id, native)
                    created = client.update(verb.doctype, match_id, native)
            elif verb.op == "method":
                # Invoke an Odoo model method (not CRUD). The record id is the first required arg.
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw
                if verb.method == "message_post":
                    client.message_post(verb.doctype, record_id, str(native.get("body", "")))
                else:  # any granted workflow method (action_post / button_validate / action_confirm / …)
                    client.call_method(verb.doctype, record_id, verb.method or "", {})
                created = {"name": record_id}
                # A method verb that declares an inverse is COMPENSABLE: mint a reversal that ROLLBACK
                # runs (reuses the generic resource.method reversal path), e.g. post_invoice→button_draft.
                if verb.reverse_method:
                    comp_override = {"resource_method": True, "target": verb.doctype, "id": record_id,
                                     "method": verb.reverse_method, "tier": verb.tier}
            else:  # op == "create"
                created = client.create(verb.doctype, native)  # the real write
        except (SystemError, NotImplementedError) as exc:
            print(f"[shim] WRITE FAILED verb={stored['verb']} -> {exc}", flush=True)
            return _envelope("STATUS", env, {"proposal": proposal_id, "state": "failed_terminal", "replayed": False})
        reversibility = "COMPENSABLE" if comp_override else comp_spec.get("reversibility", "IRREVERSIBLE")
        status_body = {"proposal": proposal_id, "state": "executed", "replayed": False}
        # EARN the verification — never assert it. Re-read the SSOT and confirm the written fields
        # actually landed. A field that didn't persist (silent backend drop) ⇒ verified:false.
        fields_written = native if verb.op in ("create", "update", "upsert") else {}
        effect_id = str(created.get("id") or created.get("name") or "")
        field_diff: list[dict[str, Any]] = []
        # COMPENSATION HONESTY. `purchase.delete_order` / `crm.delete_*` are the inverses the
        # REVERSIBLE verbs are compensated BY, so this is the path a ROLLBACK actually commits — and a
        # reversal that did not happen must never be recorded as one. A delete whose record is still
        # there afterwards is a FAILED write, not a partial one: no ledger row, no compensation token,
        # no `executed` EVENT, so no caller can read it as "compensated". (A backend that REFUSES the
        # delete already landed in the SystemError branch; this catches the quieter one — the backend
        # that accepts it and removes nothing.)
        if verb.op == "delete" and client.get(verb.doctype, effect_id) is not None:
            print(f"[shim] WRITE did NOT land: {verb.doctype}/{effect_id} still exists", flush=True)
            return _envelope("STATUS", env, {
                "proposal": proposal_id, "state": "failed_terminal", "replayed": False,
                "result": {
                    "claim": "failed", "changed": False, "verified": False,
                    "error": {"code": "WRITE_NOT_LANDED",
                              "message": f"the backend accepted the delete but {verb.doctype}/"
                                         f"{effect_id} still exists — it was NOT removed"},
                    "ssot": {"system": SYSTEM, "read_after_write": True},
                }})
        if verb.op == "delete":
            unverified, verified, did_read = [], True, True  # witnessed gone, just above
        elif fields_written and effect_id:
            unverified, field_diff = _verify_and_diff(client, verb.doctype, effect_id, before_image, fields_written)
            verified, did_read = (not unverified), True
        else:  # method ops (e.g. log_note): executed via the call, no field-level read-back claimed
            unverified, verified, did_read = [], True, False
        ssot: dict[str, Any] = {"system": SYSTEM, "read_after_write": did_read}
        if unverified:
            ssot["unverified_fields"] = unverified
        if field_diff:
            ssot["fields"] = field_diff
        result = {
            "claim": "success" if verified else "partial",
            "changed": bool(fields_written) or verb.op in ("delete", "method"),
            "verified": verified,
            "entity": entity_ref(verb, created),
            "ssot": ssot,
        }
        if unverified:
            result["unverified_fields"] = unverified
        comp_block = {"reversibility": reversibility}  # every effect declares its reversibility honestly
        if reversibility != "IRREVERSIBLE":  # mint a reversal handle the owner/agent can ROLLBACK
            comp_token = uuid4().hex[:16]
            # before-image reversals carry the captured restore; verb-mapped ones (create->delete)
            # carry the committed entity so compensate() can target the record.
            state.compensations[comp_token] = comp_override or {
                "verb": stored["verb"], "result": {"entity": result["entity"]}}
            comp_block["token"] = comp_token  # token present only when actually reversible
        status_body["compensation"] = comp_block
        result["compensation"] = comp_block
        status_body["result"] = result  # surface the SSOT entity + system-of-record to the committer
        state.ledger[key] = status_body
        state.executed.add(proposal_id)  # so GET /status reports executed, not just proposed
        sequence = state.next_sequence(env.get("workspace", ""))
        emitter.emit(
            _envelope(
                "EVENT",
                env,
                {"event": "executed", "severity": "info", "proposal": proposal_id, "result": result},
            ),
            sequence,
        )
        return _envelope("STATUS", env, status_body)

    @app.post("/nil/v0.1/query")
    def query(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        bind_tenant(env.get("workspace") or None)  # route reads to THIS workspace's vault creds
        body = env.get("body", {})
        # Generic resource.read (universal): list/inspect any provisioned target, optional field match.
        if body.get("verb") == "resource.read":
            qargs = body.get("args", {}) or {}
            target = _resolve_target(qargs.get("target"))
            # The LEGACY raw read (whole-record list) stays bounded to the writable skeleton — pulling
            # raw salaries/payments from an arbitrary model would re-open the 590 KB flood AND leak
            # sensitive fields. Universal, projected, sensitivity-gated reads flow through nil.* instead.
            if not target or not governance.reads_allowed_raw(target) or not client.exists(target):
                raise HTTPException(status_code=404, detail=f"unknown or undeclared target: {target}")
            rows = client.list(target, qargs.get("match") or None)
            return {"data": {"target": target, "count": len(rows), "items": rows}}
        verb = QUERY_VERBS.get(body.get("verb"))
        if verb is None:
            raise HTTPException(status_code=404, detail="unknown query verb")
        args = body.get("args", {}) or {}
        missing = verb.missing(args)
        if missing:  # a read that cannot run is a structured refusal, never a 500 (and never an empty
            return {"data": {  # answer — "nothing here" and "I could not look" are different answers)
                "outcome": "refused",
                "code": "MISSING_ARGS",
                "message": f"{verb.verb} requires: {', '.join(missing)}",
            }}
        return {"data": verb.run(client, args)}  # bare { data }

    @app.get("/nil/v0.1/status/{proposal_id}")
    def status(proposal_id: str, authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        if proposal_id in state.executed:
            current = "executed"
        elif proposal_id in state.proposals:
            current = "pending"  # proposed, not yet committed
        else:
            current = "expired"
        return _envelope(
            "STATUS",
            {"grant": "", "workspace": ""},
            {"proposal": proposal_id, "state": current, "replayed": True},
        )

    @app.post("/nil/v0.1/rollback")
    def rollback(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        # ROLLBACK requests a governed reversal: it never writes. We answer with a PROPOSAL (the
        # compensation preview); committing THAT proposal via /commit executes the reversal — so
        # "no silent write" holds even when undoing. An unmapped (IRREVERSIBLE) effect is refused.
        _auth(authorization)
        body = env.get("body", {})
        token = body.get("compensation_token", "")
        committed = state.compensations.get(token)
        if committed is None:
            return _refusal(env, "COMPENSATION_EXPIRED", f"unknown or expired compensation token: {token}")
        if committed.get("resource_method"):  # workflow-method reversal — preview the inverse method call
            target, rid, method = committed["target"], committed["id"], committed["method"]
            pid = uuid4().hex[:16]
            state.proposals[pid] = {"verb": "resource.method", "resource_method": True,
                                    "tier": committed.get("tier", "HIGH"),
                                    "args": {"target": target, "id": rid, "method": method}}
            return _envelope("PROPOSAL", env, {
                "outcome": "proposal", "id": pid, "verb": "resource.method",
                "tier": committed.get("tier", "HIGH"),
                "preview": {"en": f"Reverse: call {method} on {target}/{rid}",
                            "ar": f"عكس: استدعاء {method} على {target}/{rid}"},
                "resolved": {"target": target, "id": rid, "method": method},
                "modifiable": [], "expires_at": _now()})
        if committed.get("resource"):  # generic-CRUD reversal — preview the synthesized compensating verb
            rev_verb, rev_args = committed["rev_verb"], committed["rev_args"]
            rop = rev_verb.split(".", 1)[1]
            pid = uuid4().hex[:16]
            state.proposals[pid] = {"verb": rev_verb, "args": rev_args, "resource": True}
            en, ar = _resource_phrase(rop, rev_args["target"], rev_args)
            return _envelope("PROPOSAL", env, {
                "outcome": "proposal", "id": pid, "verb": rev_verb,
                "tier": {"create": "MEDIUM", "update": "MEDIUM", "delete": "HIGH"}[rop],
                "preview": {"en": en, "ar": ar}, "resolved": rev_args, "modifiable": [], "expires_at": _now()})
        verb_name = committed["verb"]
        try:
            comp_args = compensate(verb_name, committed["result"])
        except NotImplementedError:
            return _refusal(env, "IRREVERSIBLE", f"{verb_name} cannot be reversed")
        comp_verb_name = COMPENSATIONS[verb_name]["verb"]
        comp_verb = WRITE_VERBS.get(comp_verb_name)
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {"verb": comp_verb_name, "args": comp_args}  # the reversal, not yet committed
        preview = comp_verb.preview(comp_args) if comp_verb is not None else {"en": f"reverse {verb_name}", "ar": f"عكس {verb_name}"}
        return _envelope(
            "PROPOSAL",
            env,
            {
                "outcome": "proposal",
                "id": proposal_id,
                "verb": comp_verb_name,
                "tier": comp_verb.tier if comp_verb is not None else "HIGH",
                "preview": preview,
                "resolved": comp_args,
                "modifiable": [],
                "expires_at": _now(),
            },
        )

    @app.get("/healthz")
    def healthz() -> Response:
        return Response(status_code=200)

    @app.get("/nil/v0.1/describe")
    def describe() -> dict[str, Any]:
        """Discovery handshake (no auth): verbs + live readiness/shape of each native target.
        Lets the kernel/any client connect uniformly — reachable, conformant, provisioned."""
        # Advertise EXACTLY the committable WRITE skeleton: the resource.* family + the curated verbs,
        # and the governed writable targets resource.* is bounded to. advertised ≡ committable for
        # writes — describe() is the single source of truth for what this adapter will actually commit.
        # (Reads are universal via nil.* and not enumerated here — discovery is per-model, on demand.)
        targets: dict[str, Any] = {}
        for t in governance.writable_targets():
            try:
                s = client.schema(t)  # live skeleton — needs a bound tenant's creds
            except Exception:  # noqa: BLE001 — multi-tenant: no tenant bound on the bare handshake,
                s = None       # so the live shape is unknown here; verbs (the conformance surface) still stand
            targets[t] = {"exists": s is not None, "fields": s or []}
        return {
            "nil": NIL,
            "system": SYSTEM,
            "verbs": list(RESOURCE_VERBS) + sorted(WRITE_VERBS) + sorted(QUERY_VERBS),
            # Contract conformance (plan C1): the DECLARED per-verb arg surface, so the control
            # plane can check a capability's cycle provides every arg this backend requires —
            # CONTRACT_MISMATCH at readiness instead of a silent failure after approval.
            # `tier` and `reversibility` are CONTRACT, not law: facts about what this backend can do
            # and can undo. The control plane's registry DECIDES the governance tier and the approvers
            # (capability.risk + the strategy the owner authors) and reads these as the fail-closed
            # floor — an undeclared tier counts as HIGH, an undeclared reversibility as IRREVERSIBLE
            # (`nilscript.capability.wrap`). Reversibility was ABSENT here, so every reversible verb
            # registered as IRREVERSIBLE: the platform held compensations it could not know it had.
            "verb_details": [
                {"verb": v.verb, "tier": v.tier, "target": v.doctype,
                 "required": list(v.required),
                 "reversibility": (
                     "COMPENSABLE" if v.reverse_method
                     else COMPENSATIONS.get(v.verb, {}).get("reversibility", "IRREVERSIBLE")
                 )}
                for _, v in sorted(WRITE_VERBS.items())
            ],
            # READS, declared as reads. They carry NO tier and NO reversibility — a read has no effect
            # to govern or undo — and `effect: "read"` says so EXPLICITLY, so no consumer has to infer
            # it from absence (absence in the effect contract above fail-closes to IRREVERSIBLE, which
            # would register a non-effecting document fetch as an unreversible write).
            # `returns: "document"` means the verb hands back the ERP's OWN rendered bytes + their
            # sha256 — the attachment a governed send must use, never a document we render ourselves.
            "query_verb_details": [
                {"verb": v.verb, "effect": v.effect, "target": v.target,
                 "required": list(v.required), "returns": v.returns,
                 **({"report": v.report} if v.report else {})}
                for _, v in sorted(QUERY_VERBS.items())
            ],
            # The RESOURCES this backend can be the system of record for, and the native model it
            # spells each as (Wave A). Authority names the resource; the adapter keeps its vocabulary.
            "resources": RESOURCES,
            "targets": targets,
        }

    return app
